<?php

/**
 * @file
 * Adds Meetup feed parsers to the Feeds module.
 */

/**
 * Implements ctools_plugin_api().
 */
function feeds_meetup_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_meetup_feeds_plugins() {
  $info = array();
  $info['FeedsMeetupEventParser'] = array(
    'name' => 'Meetup parser: Events',
    'description' => 'Parse Meetup event feeds.',
    'help' => 'Parse Meetup event XML feeds using XPath.',
    'handler' => array(
      'parent' => 'FeedsMeetupParserBase',
      'class' => 'FeedsMeetupEventParser',
      'file' => 'FeedsMeetupEventParser.inc',
      'path' => drupal_get_path('module', 'feeds_meetup'),
    ),
  );
  $info['FeedsMeetupGroupParser'] = array(
    'name' => 'Meetup parser: Groups',
    'description' => 'Parse Meetup group feeds.',
    'help' => 'Parse Meetup group XML feeds using XPath.',
    'handler' => array(
      'parent' => 'FeedsMeetupParserBase',
      'class' => 'FeedsMeetupGroupParser',
      'file' => 'FeedsMeetupGroupParser.inc',
      'path' => drupal_get_path('module', 'feeds_meetup'),
    ),
  );
  $info['FeedsMeetupVenueParser'] = array(
    'name' => 'Meetup parser: Venues',
    'description' => 'Parse Meetup venue feeds.',
    'help' => 'Parse Meetup venue XML feeds using XPath.',
    'handler' => array(
      'parent' => 'FeedsMeetupParserBase',
      'class' => 'FeedsMeetupVenueParser',
      'file' => 'FeedsMeetupVenueParser.inc',
      'path' => drupal_get_path('module', 'feeds_meetup'),
    ),
  );
  return $info;
}

/**
 * Implements hook_help().
 */
function feeds_meetup_help($path, $arg) {
  $ret_val = '';
  switch ($path) {
    case 'admin/help#feeds_meetup':
      $ret_val = '<h3>' . t('About') . '</h3>';
      $ret_val .= '<p>' . t('Feeds: Meetup extends Feeds and Feeds XPath Parser to consume data from Meetup.com XML feeds.') . '</p>';
      break;
  }
  return $ret_val;
}

/**
 * Adjust millisecond-based Unix timestamp to second-based.
 */
function _feeds_meetup_msToSeconds($milliseconds) {
  return $milliseconds / 1000;
}
