<?php if($is_front): ?>
	<?php if (!empty($title_prefix) || !empty($title) || !empty($title_suffix)): ?>
		<div class="page-title <?php print $title_class; ?> <?php print $title_container; ?>">
			<?php print render($title_prefix); ?>
			<?php if (!empty($title)): ?>
				<h1 class="page-header"><?php print $title; ?></h1>
			<?php endif; ?>
			<?php print render($title_suffix); ?>
		</div>
	<?php endif; ?>
<?php else: ?>
	<?php if(!$title_placement): ?>
		<?php if (!empty($title_prefix) || !empty($title) || !empty($title_suffix)): ?>
			<div class="page-title <?php print $title_class; ?>">
				<div class="page-title-container <?php print $title_container; ?>">
					<div class="page-title-inner">
						<?php print render($title_prefix); ?>
						<?php if (!empty($title)): ?>
							<h1 class="page-header"><?php print $title; ?></h1>
						<?php endif; ?>
						<?php print render($title_suffix); ?>
					</div>
				</div>
			</div>
		<?php endif; ?>
	<?php else: ?>
		<?php if (!empty($title)): ?>
			<div class="page-title <?php print $title_class; ?>">
				<div class="page-title-container <?php print $title_container; ?>">
					<div class="page-title-inner <?php print $title_row; ?>">
						<?php print render($title_prefix); ?>
						<?php if (!empty($title)): ?>
							<h1 class="page-header"><?php print $title; ?></h1>
						<?php endif; ?>
						<?php print render($title_suffix); ?>
					</div>
				</div>
			</div>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>