<?php
/**
 * @file
 * Code for the Techmill Coworkers feature.
 */

include_once 'techmill_coworkers.features.inc';

/**
 * Implements hook_ds_fields_info().
 */
function techmill_coworkers_ds_fields_info($entity_type) {
	$fields = array();
	$fields['coworker_social_links'] = array(
		'title' => t('TechMill: Coworker Social Links'),
		'field_type' => DS_FIELD_TYPE_FUNCTION,
		//'ui_limit' => 'coworking_member|*',
		'function' => '_techmill_coworkers_ds_field_coworker_social_links',
		);

	return array('node' => $fields);
}

/**
 * Custom field displaying a coworking member social media accounts.
 */
function _techmill_coworkers_ds_field_coworker_social_links($field) {
	if (isset($field['entity_type']) && $field['entity_type'] == 'node') {
		$entity = $field['entity'];

		// Get social links
		$social = array();
		$social['twitter'] = (!empty($entity->field_coworking_twitter)) ? $entity->field_coworking_twitter['und'][0]['safe_value'] : '';
		$social['facebook'] = (!empty($entity->field_coworking_facebook)) ? $entity->field_coworking_facebook['und'][0]['safe_value'] : '';
		$social['linkedin'] = (!empty($entity->field_coworking_linkedin)) ? $entity->field_coworking_linkedin['und'][0]['safe_value'] : '';
		$social['github'] = (!empty($entity->field_coworking_github)) ? $entity->field_coworking_github['und'][0]['safe_value'] : '';
		$social['youtube'] = (!empty($entity->field_coworking_youtube)) ? $entity->field_coworking_youtube['und'][0]['safe_value'] : '';
		// Remove empty links
		$social = array_filter($social);
		$social_list = array(
			'attributes' => array(
				'class' => 'coworker-social-media',
				),
			);

		foreach ($social as $key => $value) {
			$social_list['items'][] = _techmill_coworkers_social_wrapper($key, $value);
		}

		return theme('item_list', $social_list);
	}
	return FALSE;
}

/*
 * Helper function to create icon wrappers.
 */
function _techmill_coworkers_social_wrapper($social, $value) {
	$output = '<a class="social-icon" href="http://'.$social.'.com/'.$value.'" title="'.ucfirst($social).'" target="_blank"><i class="icon fontello social-'.$social.'"></i></a>';

	return $output;
}